import React, { useState } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { FileText, Download, Calendar } from 'lucide-react';
import { jsPDF } from 'jspdf';
import * as XLSX from 'xlsx';
import AgentPanel from '../components/AgentPanel';

const Reports = () => {
  const user = JSON.parse(localStorage.getItem('user') || '{}');
  const role = user.role || 'eb_officer';

  if (role !== 'eb_officer') {
    return (
      <div className="flex flex-col items-center justify-center min-h-[400px] text-center glass p-8 rounded-2xl">
        <h2 className="text-2xl font-bold text-white mb-2">Access Denied</h2>
        <p className="text-gray-400">This page is restricted to Electricity Board Officers.</p>
      </div>
    );
  }

  const [successMessage, setSuccessMessage] = useState('');

  const showSuccess = (msg) => {
    setSuccessMessage(msg);
    setTimeout(() => setSuccessMessage(''), 4000);
  };

  const handleDownload = (type, title) => {
    const reportId = `REP-${Math.floor(100000 + Math.random() * 900000)}`;
    const timestamp = new Date().toLocaleString();
    const generatedBy = 'Admin User (Grid Operations Manager)';

    try {
      if (type === 'PDF') {
        const doc = new jsPDF();
        
        // Header / Logo
        doc.setFontSize(20);
        doc.setTextColor(37, 99, 235); // Blue
        doc.text('EcoGrid AI', 20, 20);
        
        doc.setFontSize(10);
        doc.setTextColor(100, 116, 139);
        doc.text('Smart Town Energy Management System', 55, 20);
        
        // Report Title & Metadata
        doc.setFontSize(14);
        doc.setTextColor(15, 23, 42);
        doc.text(title, 20, 32);
        
        doc.setFontSize(9);
        doc.setTextColor(100, 116, 139);
        doc.text(`Report ID: ${reportId}`, 20, 40);
        doc.text(`Generated Date & Time: ${timestamp}`, 20, 45);
        doc.text(`Generated By: ${generatedBy}`, 20, 50);
        
        doc.setDrawColor(226, 232, 240);
        doc.line(20, 54, 190, 54);
        
        // Section 1: Town Overview
        doc.setFontSize(11);
        doc.setTextColor(37, 99, 235);
        doc.text('Town Overview', 20, 62);
        
        doc.setFontSize(9);
        doc.setTextColor(51, 65, 85);
        doc.text('• Total Energy Consumption: 72.5 MWh', 22, 69);
        doc.text('• Current Power Demand: 3.8 MW', 22, 74);
        doc.text('• Renewable Energy Contribution: 12% (Solar/Wind yield)', 22, 79);
        doc.text('• Carbon Reduction: 18.5 Tons of CO2', 22, 84);
        doc.text('• Grid Health: Healthy', 22, 89);
        
        doc.line(20, 94, 190, 94);
        
        // Section 2: Zone-wise Energy Consumption
        doc.setFontSize(11);
        doc.setTextColor(37, 99, 235);
        doc.text('Zone-wise Energy Consumption', 20, 102);
        
        doc.setFontSize(9);
        doc.setTextColor(51, 65, 85);
        doc.text('• Residential Zone: 32.4 MWh (45% of total)', 22, 109);
        doc.text('• Commercial Zone: 18.1 MWh (25% of total)', 22, 114);
        doc.text('• Industrial Zone: 22.0 MWh (30% of total)', 22, 119);
        
        doc.line(20, 124, 190, 124);
        
        // Section 3: Transformer Summary
        doc.setFontSize(11);
        doc.setTextColor(37, 99, 235);
        doc.text('Transformer Summary', 20, 132);
        
        doc.setFontSize(9);
        doc.setTextColor(51, 65, 85);
        doc.text('• Transformer A: Load 72%, Voltage 11kV, Current 94A, Temp 48°C, Health Healthy', 22, 139);
        doc.text('• Transformer B: Load 91%, Voltage 11kV, Current 126A, Temp 66°C, Health High Load', 22, 144);
        doc.text('• Transformer C: Load 98%, Voltage 11kV, Current 147A, Temp 79°C, Health Critical', 22, 149);
        doc.text('• Transformer D: Load 45%, Voltage 11kV, Current 58A, Temp 42°C, Health Healthy', 22, 154);
        
        doc.line(20, 159, 190, 159);
        
        // Section 4: AI Insights
        doc.setFontSize(11);
        doc.setTextColor(37, 99, 235);
        doc.text('AI Insights', 20, 167);
        
        doc.setFontSize(9);
        doc.setTextColor(51, 65, 85);
        doc.text('• Transformer B is operating at high load.', 22, 174);
        doc.text('• Shift 12% load to Transformer D.', 22, 179);
        doc.text('• Evening demand expected to increase by 9%.', 22, 184);
        
        doc.line(20, 189, 190, 189);
        
        // Section 5: Energy Saving Recommendations
        doc.setFontSize(11);
        doc.setTextColor(37, 99, 235);
        doc.text('Energy Saving Recommendations', 20, 197);
        
        doc.setFontSize(9);
        doc.setTextColor(51, 65, 85);
        doc.text('• Reduce peak-hour consumption.', 22, 204);
        doc.text('• Improve transformer load balancing.', 22, 209);
        doc.text('• Increase renewable energy usage.', 22, 214);
        
        doc.line(20, 222, 190, 222);
        
        // Footer
        doc.setFontSize(10);
        doc.setTextColor(37, 99, 235);
        doc.text('EcoGrid AI', 20, 232);
        
        doc.setFontSize(8);
        doc.setTextColor(148, 163, 184);
        doc.text('Smart Town Energy Management System — Confidential', 20, 237);
        
        doc.save(`${title.replace(/\s+/g, '_').toLowerCase()}_${reportId}.pdf`);
        showSuccess(`${title} generated and downloaded successfully!`);
        
      } else if (type === 'Excel') {
        const wb = XLSX.utils.book_new();
        
        // Sheet 1: Town Overview
        const townOverviewData = [
          { 'Metric Parameter': 'Total Energy Consumption', 'Current Value': '72.5 MWh' },
          { 'Metric Parameter': 'Current Power Demand', 'Current Value': '3.8 MW' },
          { 'Metric Parameter': 'Renewable Energy Contribution', 'Current Value': '12%' },
          { 'Metric Parameter': 'Carbon Reduction', 'Current Value': '18.5 Tons of CO2' },
          { 'Metric Parameter': 'Grid Health Status', 'Current Value': 'Healthy' }
        ];
        const ws1 = XLSX.utils.json_to_sheet(townOverviewData);
        XLSX.utils.book_append_sheet(wb, ws1, "Town Overview");
        
        // Sheet 2: Zone Energy Consumption
        const zoneData = [
          { 'Town Sector': 'Residential Zone', 'Consumption today (MWh)': 32.4, 'Grid Load Share': '45%' },
          { 'Town Sector': 'Commercial Zone', 'Consumption today (MWh)': 18.1, 'Grid Load Share': '25%' },
          { 'Town Sector': 'Industrial Zone', 'Consumption today (MWh)': 22.0, 'Grid Load Share': '30%' }
        ];
        const ws2 = XLSX.utils.json_to_sheet(zoneData);
        XLSX.utils.book_append_sheet(wb, ws2, "Zone Energy Consumption");
        
        // Sheet 3: Transformer Performance
        const transformerData = [
          { 'Transformer Name': 'Transformer A', 'Current Load': '72%', 'Voltage': '11 kV', 'Current': '94 A', 'Oil Temperature': '48°C', 'Health Score': '95/100', 'Connected Houses': 124, 'Fault History': 'None', 'Predicted Failure Risk': '2%', 'AI Maintenance Recommendation': 'No maintenance required.' },
          { 'Transformer Name': 'Transformer B', 'Current Load': '91%', 'Voltage': '11 kV', 'Current': '126 A', 'Oil Temperature': '66°C', 'Health Score': '78/100', 'Connected Houses': 156, 'Fault History': '1 Minor Alert', 'Predicted Failure Risk': '8%', 'AI Maintenance Recommendation': 'Monitor winding temperature.' },
          { 'Transformer Name': 'Transformer C', 'Current Load': '98%', 'Voltage': '11 kV', 'Current': '147 A', 'Oil Temperature': '79°C', 'Health Score': '45/100', 'Connected Houses': 182, 'Fault History': '3 Overloads', 'Predicted Failure Risk': '42%', 'AI Maintenance Recommendation': 'Shift load to D within 48h.' },
          { 'Transformer Name': 'Transformer D', 'Current Load': '45%', 'Voltage': '11 kV', 'Current': '58 A', 'Oil Temperature': '42°C', 'Health Score': '99/100', 'Connected Houses': 84, 'Fault History': 'None', 'Predicted Failure Risk': '1%', 'AI Maintenance Recommendation': 'Standby healthy.' }
        ];
        const ws3 = XLSX.utils.json_to_sheet(transformerData);
        XLSX.utils.book_append_sheet(wb, ws3, "Transformer Performance");
        
        // Sheet 4: AI Recommendations
        const aiData = [
          { 'Insight ID': 1, 'Target Asset': 'Transformer B', 'AI Recommendation': 'Transformer B is operating at high load. Shift 12% load to Transformer D.' },
          { 'Insight ID': 2, 'Target Asset': 'System Grid', 'AI Recommendation': 'Evening demand expected to increase by 9%.' },
          { 'Insight ID': 3, 'Target Asset': 'Consumer Management', 'AI Recommendation': 'Reduce peak-hour consumption.' },
          { 'Insight ID': 4, 'Target Asset': 'Grid Operation', 'AI Recommendation': 'Improve transformer load balancing.' },
          { 'Insight ID': 5, 'Target Asset': 'Generation Mix', 'AI Recommendation': 'Increase renewable energy usage.' }
        ];
        const ws4 = XLSX.utils.json_to_sheet(aiData);
        XLSX.utils.book_append_sheet(wb, ws4, "AI Recommendations");

        XLSX.writeFile(wb, `${title.replace(/\s+/g, '_').toLowerCase()}_${reportId}.xlsx`);
        showSuccess(`${title} generated and downloaded successfully!`);
      }
    } catch (err) {
      console.error('Report generation failed:', err);
    }
  };

  return (
    <div className="space-y-6 pb-10">
      <div className="flex justify-between items-end mb-8">
        <div>
          <h1 className="text-3xl font-bold text-white mb-2">Reports & Analytics</h1>
          <p className="text-gray-400">Generate AI-powered reports for town-wide energy distribution, transformer health, and electricity usage.</p>
        </div>
      </div>

      {/* Success Banner */}
      <AnimatePresence>
        {successMessage && (
          <motion.div 
            initial={{ opacity: 0, y: -20 }}
            animate={{ opacity: 1, y: 0 }}
            exit={{ opacity: 0, y: -20 }}
            className="p-4 bg-success/20 border border-success/30 text-success rounded-xl text-sm text-left mb-6 font-medium"
          >
            {successMessage}
          </motion.div>
        )}
      </AnimatePresence>

      <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
        {[
          { 
            title: 'Daily Town Energy Report', 
            desc: 'Comprehensive report of today\'s electricity consumption across all residential, commercial, and industrial zones.', 
            type: 'PDF' 
          },
          { 
            title: 'Transformer Performance Report', 
            desc: 'AI-generated health analysis and load distribution report for all town transformers.', 
            type: 'Excel' 
          },
          { 
            title: 'Monthly Energy Analytics Report', 
            desc: 'Monthly analysis of town-wide electricity usage, renewable energy contribution, and operational efficiency.', 
            type: 'PDF' 
          },
        ].map((report, idx) => (
          <motion.div 
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: idx * 0.1 }}
            key={idx} 
            className="glass p-6 rounded-2xl hover:border-primary/50 transition-colors group text-left"
          >
            <div className="p-3 bg-white/5 rounded-xl w-fit mb-4 group-hover:bg-primary/20 transition-colors">
               <FileText className="w-6 h-6 text-primary" />
            </div>
            <h3 className="text-lg font-bold text-white mb-2">{report.title}</h3>
            <p className="text-sm text-gray-400 mb-6">{report.desc}</p>
            <div className="flex justify-between items-center">
              <span className="text-xs text-gray-500 flex items-center gap-1"><Calendar className="w-3 h-3"/> Auto-generated</span>
              <button 
                onClick={() => handleDownload(report.type, report.title)}
                className="flex items-center gap-2 px-3 py-1.5 bg-primary/20 text-primary border border-primary/30 rounded-lg hover:bg-primary/30 transition-colors text-sm font-medium"
              >
                <Download className="w-4 h-4" /> {report.type}
              </button>
            </div>
          </motion.div>
        ))}
      </div>
      {/* AI Agent Panels */}
      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        <AgentPanel
          agentName="Smart Decision Support Agent"
          agentColor="text-cyan-400"
          agentBg="bg-cyan-400/20"
          role="eb_officer"
          suggestedQueries={['Generate operational recommendations', 'Analyze town energy consumption', 'Recommend resource allocation', 'Show transformer utilization']}
          defaultOpen={true}
        />
        <AgentPanel
          agentName="Carbon Analytics Agent"
          agentColor="text-success"
          agentBg="bg-success/20"
          role="eb_officer"
          suggestedQueries={['Generate sustainability report', 'Show CO₂ emissions', 'Compare monthly emissions']}
        />
        <AgentPanel
          agentName="Anomaly Detection Agent"
          agentColor="text-orange-400"
          agentBg="bg-orange-400/20"
          role="eb_officer"
          suggestedQueries={['Show full anomaly report', 'Detect possible electricity theft', 'Show abnormal consumption patterns']}
        />
      </div>
    </div>
  );
};

export default Reports;
